<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="farover">

<material name="white">
    <color rgba="1 1 1 1"/>
</material>

<material name="orange">
    <color rgba="1 0.3 0.1 1"/>
</material>

<material name="blue">
    <color rgba="0.2 0.2 1 1"/>
</material>

<material name="black">
    <color rgba="0 0 0 1"/>
</material>

<xacro:property name="base_width" value="0.31"/>

<xacro:property name="base_length" value="0.42"/>

<xacro:property name="base_height" value="0.18"/>

<xacro:property name="wheel_radius" value="0.10"/>

<xacro:property name="wheel_width" value="0.04"/>

<xacro:property name="wheel_ygap" value="0.025"/>

<xacro:property name="wheel_zoff" value="0.05"/>

<xacro:property name="wheel_xoff" value="0.12"/>


<xacro:property name="caster_xoff" value="0.14"/>

<link name="base_link"></link>

<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
</joint>

<link name="chassis">

    <visual>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
    </visual>

    <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>

</link>

<gazebo reference="chassis">
    <material>Gazebo/White</material>
</gazebo>

<!-- Wheels -->

<xacro:macro name="wheel" params="prefix x_reflect y_reflect">

<link name="${prefix}_link">

  <visual>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>

    <geometry>

        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>

    </geometry>

    <material name="Gray">

      <color rgba="0.5 0.5 0.5 1.0"/>

    </material>
  </visual>

  <collision>
    <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
    <geometry>

      <cylinder radius="${wheel_radius}" length="${wheel_width}"/>

    </geometry>
  </collision>

  <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>

</link>


<joint name="${prefix}_joint" type="continuous">

  <parent link="chassis"/>

  <child link="${prefix}_link"/>

  <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>

  <axis xyz="0 1 0"/>

</joint>

</xacro:macro>


<xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />

<xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

<!-- CASTER WHEEL -->

<link name="front_caster">

    <visual>
      <geometry>

        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>

      </geometry>

      <material name="Cyan">

        <color rgba="0 1.0 1.0 1.0"/>

      </material>
    </visual>

    <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>

            <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>

        </geometry>
    </collision>
  
    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>

  </link>

    <gazebo reference="front_caster">
        <material>Gazebo/Black</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>


  <joint name="caster_joint" type="fixed">

    <parent link="chassis"/>

    <child link="front_caster"/>

    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>

  </joint>

</robot>
